-
  name: Media Dynamics
  business_number: 51 123 24 123
  address:
   lines: |
      Unit 4,
      178 Albion Rd
   city    : Windsor
   state   : QLD
   postal  : 4030
   country: Australia
  contact:
   name: Christopher Beck
   email: test@jwije.com
  alias: MD
  rate: 30
-
 name: TipTop Select
 business_number: 45 443 23 123
 address:
   lines: |
      2 Witham Road
   city    : Maleny
   state   : QLD
   postal  : 4552
   country: Australia
 contact:
  name: Rafaela Giebler
  email: test@jwije.com
 alias: TTS
 rate: 35