-
  name: Media Dynamics
  business_number: 51 123 24 123
  address:
   lines: |
      52 Walkman Dr.
      Suite #292
   city    : West End
   state   : QLD
   postal  : 4101
   country: Australia
  contact:
   name: C Brown
   email: c.brown@test.com
  alias: MD
  rate: 30
-
 name: TipTop Select
 business_number: 45 443 23 123
 address:
   lines: |
      2 Roger Road
   city    : Maleny
   state   : QLD
   postal  : 4552
   country: Australia
 contact:
  name: R Germaign
  email: r.germaign@test.com
 alias: TTS
 rate: 35